Added a feature for bug reporting
JoFrhwld/FAVE pull request #72
Opened 2022-09-30 06:51 UTC by DerMoehre

I added a bug reporting form and a description of the bug triage. 

I hope, that I understood the task correctly.

2022-09-30 19:52 UTC, chrisbrickhouse requested changes
This is amazing! I didn't know about this feature of GitHub, so thank you for introducing us to it. I look forward to learning more about it with you. I've reviewed the code and left feedback on particular lines with project-specific improvements. The form is great, it includes questions for all of the things that make a good bug report, but many of our users are not programmers and so our form should do more to cater to that user base.

In general, our philosophy on bug reports is that the barrier to reporting a bug should be low, otherwise users may see the form and decide to not report a bug at all. A poor bug report is better than no bug report. Even a duplicate bug report can give us helpful information. So there are some comments about making required questions optional and some wording suggestions.

I hope it's not too much feedback! I tried to be helpful and give some suggestions where I could which is why some comments look very long. If you have any questions or think I'm wrong on something, feel free to follow up in a reply. Like I said, this is an amazing start and I really appreciate this contribution!

2022-09-30 19:52 UTC, chrisbrickhouse commented on README.md
> +You can fill in a bug report at the issue tab.
We should probably include a link to the issues page because not everyone will know how to find it.

2022-09-30 19:52 UTC, chrisbrickhouse commented on README.md
> +We will work on the bugs with a bug triage. This means, that every bug is rated after its importance of fixing. Those bugs with the highest rating are solved first. This can lead to a bit dely in sol
We don't have a formal triage system, but you're right that we triage them. It would be better to describe triage more informally. Something like: "There may be a delay between when a bug is reported and when a bug is resolved. Developers prioritize bugs based on difficulty, importance, and other factors, so bug reports are usually not handled in the order they are received."

2022-09-30 19:52 UTC, chrisbrickhouse commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +description: File a bug report here
Some people do not have a good understanding of what a "bug" is in our context ("software does not operate the way we say that it operates"), so the description should be more user friendly.

2022-09-30 19:52 UTC, chrisbrickhouse commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        required: true
Make it optional rather than required. We'd like them to search first, but not everyone has the time, skills, or confidence to do that. Worst case we close as duplicate and point them somewhere else.

2022-09-30 19:52 UTC, chrisbrickhouse commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      label: Is there an existing issue for this?
Question should focus on what the user has done, rather than focusing on whether something exists or not. Users may not feel confident that they've done an adequate search and give up. Compare that to a question like "Did you search for similar bugs?" The user has personal knowledge of whether they performed a search or not so it's easier to answer while giving us about the same information.

2022-09-30 19:52 UTC, chrisbrickhouse commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      description: Tell us what bug you encountered and what should have happened
Split these up into two questions: "Description/what happened" and "What did you expect to happen". Narrow questions will help us get better data.

2022-09-30 19:52 UTC, chrisbrickhouse commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      required: true
Make this optional, not everyone will know what this means or how to write it. If they can, great, if not, let them file a report and we can follow up.

2022-09-30 19:52 UTC, chrisbrickhouse commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      description: Steps to reproduce the behavior.
Can this be described in more detail? Many of our users will not be familiar with "steps to reproduce" as a term, and even if they know what it means, they might not know their system well enough to write out all the steps they took.

2022-09-30 19:52 UTC, chrisbrickhouse commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        Thanks for taking the time to fill out this bug report!
More of a note to myself: we should include a warning like "This report will be public. Do not include confidential research data in this report. This information might be in file names, transcripts, and some log outputs so double check before you submit!"

2022-10-01 10:30 UTC, DerMoehre commented on README.md
> +You can fill in a bug report at the issue tab.
I will add a link to the issue tab :)

2022-10-01 10:32 UTC, DerMoehre commented on README.md
> +We will work on the bugs with a bug triage. This means, that every bug is rated after its importance of fixing. Those bugs with the highest rating are solved first. This can lead to a bit dely in sol
Ah I see :) I will copy your text, as it sounds really good

2022-10-01 10:41 UTC, DerMoehre commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      description: Steps to reproduce the behavior.
I actually don't know, how the labels work right now. I added a bit longer description, which should be easier to understand

2022-10-01 10:43 UTC, DerMoehre commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        Thanks for taking the time to fill out this bug report!
I did not change anything here. If you want, we can add this disclaimer also into the bug report.

2022-10-01 10:53 UTC, DerMoehre commented
I changed some things in the files. I hope it was correct, as I tried to push it again. If you can't see the changes, I will try again ;-)

2022-10-01 20:56 UTC, chrisbrickhouse requested changes
I think you accidentally committed a configuration file from VS Code, the rest of the changes LGTM so we should be able to merge once that last thing is fixed.

2022-10-01 20:56 UTC, chrisbrickhouse commented on Documents.code-workspace
> +}
Is this a config file from VS Code? I don't think you meant to commit this. You can add `*.code-workspace` to your `.gitignore` so that `git commit -a` ignores files like this.

2022-10-02 08:01 UTC, DerMoehre commented on Documents.code-workspace
> +}
Thank you! 
I added it to the .gitignore and pushed it again. I hope, it works now. 
Sorry for the inconvenience

2022-10-02 20:30 UTC, chrisbrickhouse approved these changes

2022-10-02 20:31 UTC, chrisbrickhouse commented on Documents.code-workspace
> +}
No inconvenience, it's why we do code review!

2022-10-02 20:34 UTC, merged