check for header row
JoFrhwld/FAVE pull request #73
Opened 2022-10-03 11:03 UTC by DerMoehre

I used your code to implement a small test for a header row
Also updated the code in transcriptprocessor to check for the header row and jump to the next row. 
Because sometimes, there are no rows following, the next() has also to be in a try:except block

2022-10-04 19:02 UTC, chrisbrickhouse commented on fave/align/transcriptprocessor.py
> +                    pass
Two things:

1. This approach is too cautious. Try-except should be used when we expect a specific situation could arise and want to handle that case. If we cannot handle that situation, we should let the function exit with the error code and let the parent function deal with it (and so on up the chain until it is handled or the program exits with an error). If something goes wrong with `next()` we want that to error to "bubble up" to the top of the program. See [exception handling best practices](http://codebuild.blogspot.com/2012/01/15-best-practices-about-exception.html) 4 and 9.
2. You don't want to use `next(f)` here. You can see in line 249/251 that we've already read the file into memory as `lines` so we should be working with that instead of the file. I'm realizing now that `next()` is probably the wrong approach. This function sets `self.lines` and it should be a list. If we use `next()` the type will be [an iterator](https://docs.python.org/3/library/stdtypes.html#typeiter) and not a list. So we should just remove the first entry from the list, `del lines[0]` should do the trick.

2022-10-04 19:08 UTC, chrisbrickhouse commented on tests/fave/align/test_readFile.py
> +        assert tp_obj.lines == expected
You can (and should) combine these. Notice that these loops iterate over the return of the provider functions, and notice that the provider functions return a list of lists. If you add new test cases to the list of lists returned by the provider function, you only need one of these loops. This is known as the [data provider pattern](https://medium.com/swlh/using-data-provider-pattern-for-javascript-unit-tests-1965ff8478ba).

2022-10-04 19:15 UTC, chrisbrickhouse commented on tests/fave/align/test_readFile.py
> +    ]
Following up on the above comment, notice that the parameters for the test are a list:
```python
[
  "foo\tbar...\n...4.5\t3.5", # test_text
  {
    ... # flags
  },
 ['foo...', 'Test...'] # expected
]
```
Meanwhile, that list is an entry in a list returned by the function, and each element of that list of lists is iterated over and tested. So instead of having multiple providers for a test, we can just add new test cases as entries in the list:

```python
def provide_foo():
    return [
        [ 'Test case 1'],
        [ 'Test case 2'],
        [ 'Test case 3']
    ]
```

2022-10-04 19:32 UTC, DerMoehre commented on tests/fave/align/test_readFile.py
> +    ]
Thank you :) I will read your comments and try to learn from them.

2022-10-04 19:34 UTC, DerMoehre commented on fave/align/transcriptprocessor.py
> +                print("Header row was detected")
Ah okay, necer used this :-)

2022-10-04 19:36 UTC, DerMoehre commented on fave/align/transcriptprocessor.py
> +                    pass
okay, that would also make it easier to check, if there is another line. This is why I added the extra try:except block, because I ran in some errors because there were no next lines

2022-10-05 18:11 UTC, chrisbrickhouse requested changes
LGTM. A few typos, but once those are fixed I can merge.

2022-10-05 18:11 UTC, chrisbrickhouse commented on tests/fave/align/test_transcriptprocessor.py
> +            "Foo\tBar\t0.0\t3.2\t3.2\nTest\t1.0\4.5\t3.5",
You forgot a tab: `1.0\4.5` should be `1.0\t4.5`. Same typo in the expected field (which is why the test passes) and in the following test cases.

2022-10-05 18:11 UTC, chrisbrickhouse commented on tests/fave/align/test_transcriptprocessor.py
> +        [   # test with more lines
See above. Happens twice in this line and the expected value.

2022-10-06 17:45 UTC, merged