mean_stdv ignores None element in list (extractFormants.py)
JoFrhwld/FAVE pull request #84
Opened 2022-10-11 04:59 UTC by DerMoehre

2022-10-13 04:48 UTC, DerMoehre commented
I had to change a bit in the extractFormants file to check for None in the list items. 
If we change that to numpy, I think it wil get easier, as numpy can check for None on its own.

2022-10-16 18:16 UTC, JoFrhwld requested changes
Thanks for this PR! Left some comments about just going all the way to the numpy refactor

2022-10-16 18:16 UTC, JoFrhwld commented on fave/extractFormants.py
> +                if valuelist[i] == None:
This is great, but actually I think we're safe to go ahead and replace this custom mean and standard deviation code with `np.nanmean()` and `np.nanstd()`. I think what needs to change inside `mean_stdv()` is 

1. Conversion of `valuelist` to an `np.array()`
2. Replacement of these loops and conditionals with `np.nanmean()` and `np.nanstd()`. 

```python
mean = np.nanmean(valuearray)
stdv = np.nanmean(valuearray)
```

Both the `np` functions return `np.float64` values, which as far as I can tell will be correctly utilized by the rest of the code.

2022-10-16 18:16 UTC, JoFrhwld commented on fave/extractFormants.py
> +                if valuelist[i] == None:
If you're happy to make those changes as additional commits, they should appear in this PR, and we can merge them in to also include the update to the tests as well

2022-10-16 18:16 UTC, JoFrhwld commented on tests/fave/extract/test_extractFormants.py
> +        ],
Thanks for catching this!

2022-10-16 18:24 UTC, DerMoehre commented on fave/extractFormants.py
> +                if valuelist[i] == None:
I will make those changes and push it to this PR :)

2022-10-17 05:12 UTC, DerMoehre commented
I changed the mean_stdv() to use numpy. 
The function still checks, if the array is empty. If I just use nanmean/nanstd the return value results in an error, as nan == nan is false

2022-10-17 13:08 UTC, JoFrhwld commented
Nice! At first glance this looks really really good. Will review and merge later today.

2022-10-17 13:25 UTC, DerMoehre commented
Thank you :-) you Guys are making it really easy to get more and more into this

2022-10-17 16:32 UTC, JoFrhwld approved these changes
Looks good! Just a note that `len(array)`, `array.shape` and `array.size` all have similar but slightly different behaviors for testing the length of an np array which could be useful for other error catching, but I don't think they have any performance differences so I think we'll just go ahead a merge this solution with `len()`

2022-10-17 16:35 UTC, merged